# Generated by Django 3.2 on 2022-03-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20220306_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Distance',
        ),
        migrations.AlterModelOptions(
            name='distance',
            options={'verbose_name_plural': 'Distances'},
        ),
    ]
