# Generated by Django 3.2 on 2022-03-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20220306_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('effort', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('week', models.CharField(max_length=254)),
                ('day', models.CharField(max_length=254)),
                ('distance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.distance')),
            ],
        ),
    ]
