# Generated by Django 3.2 on 2022-03-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_delete_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='week',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
