# Generated by Django 3.2 on 2022-03-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_alter_session_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='duration',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
