# Generated by Django 3.2 on 2022-03-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_userpace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPace',
        ),
    ]
