# Generated by Django 3.2 on 2022-03-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_delete_userpace'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='product_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
