# Generated by Django 3.2 on 2022-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_distance_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='instructions',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
