# Generated by Django 3.2 on 2022-04-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_distance_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='type',
        ),
    ]
