# Generated by Django 3.2 on 2022-03-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=254, null=True)),
                ('review', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
