# Generated by Django 3.2 on 2022-04-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_id',
            field=models.IntegerField(blank=True),
        ),
    ]
