# Generated by Django 3.2 on 2022-05-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
