# Generated by Django 3.2 on 2022-03-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220317_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='0'),
            preserve_default=False,
        ),
    ]
