# Generated by Django 3.2 on 2022-03-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='default_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='default_review',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='default_subject',
            new_name='subject',
        ),
    ]
