# Generated by Django 3.2 on 2022-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220319_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order_number',
            field=models.CharField(default='0', editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.CharField(default='0', editable=False, max_length=3),
            preserve_default=False,
        ),
    ]
