# Generated by Django 3.2 on 2022-03-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220319_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_id',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
