# Generated by Django 3.2 on 2022-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220319_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='0', max_length=254),
            preserve_default=False,
        ),
    ]
