# Generated by Django 3.2 on 2022-04-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_recommendation_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Recommendation_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation2', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='Recommendation_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation3', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Recommendation_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation1', to='products.product'),
        ),
    ]
