# Generated by Django 3.2 on 2022-04-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220406_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Recommendation_1',
            new_name='recommendation_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Recommendation_2',
            new_name='recommendation_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Recommendation_3',
            new_name='recommendation_3',
        ),
    ]
